### ISSUE TITLE
Commands are not recognized

### ISSUE THREAD

**Issue by francisco-simoes** [hanschen/vim-ipython-cell#11]
I used the plugin successfully for months. Now, the commands do not work anymore. The errors it gives are of the following type:
`Not an editor command: IPythonCellRun`

**Comment by hanschen** [comment]
That sounds more like an error in your setup than a bug. The most likely cause is that your Vim/Neovim doesn't have Python support. What do you get if you run

    :echo has('python')
    :echo has('python3')

in your editor?

**Comment by francisco-simoes** [comment]
You are right: it printed 0 for both.
Now that I installed pynvim the commands are recognized.
Thank you.

**Comment by hanschen** [comment]
Great. I've added a FAQ entry about this issue in case other people encounter the same issue.
