### ISSUE TITLE
Define cell tag as regex

### ISSUE THREAD

**Issue by victorkristof** [hanschen/vim-ipython-cell#12]
Hi there,

Super useful plugin, thank you for the great work!

I was just wondering whether it would be possible to define cell tags as regex?

I'm using the [percent](https://jupytext.readthedocs.io/en/latest/formats.html#the-percent-format) format for my cells, and you can define cells like this:
```python
# %% [markdown]
# This is a Markdown cell.

# %%
# This is a code cell.
print('Great plugin!')
```

I would like to do something like:
```viml
" Note the dollar sign at the end to indicate the end of line.
let g:ipython_cell_tag = '# %%$' 
```
so that `:IPythonCellPrevCell` will jump to the next code cell, ignoring the Markdown cells.

Thank you!

**Comment by hanschen** [comment]
Glad to hear that you find this plugin useful. :)

Please update the plugin and add the following to your .vimrc/init.vim:

    let g:ipython_cell_regex = 1

and see if it works for you. If there are any issues, feel free to re-open this.

**Comment by victorkristof** [comment]
Works great! One improvement would be to specify in the documentation that it expects a *Python* regex, and not a Vim one. They use different engines and I spent a while figuring this out :)

In my use case, for the `percent` format, I have three cases:
```
# %% [markdown]
# %% Code cell with optional title.
# %%
```
The last line is a code cell without the optional title.
To match the two code cells and not the Markdown one, I set 
```
let g:ipython_cell_tag = '^# %%( [^[].*)?$'
```
But in Vim (`magic`) regex this would have been
```
let g:ipython_cell_tag = '^# %%\( [^[].*\)\?$'
```

Thanks for being so quick at implementing this, by the way!

**Comment by hanschen** [comment]
Good point, I've clarified the README and docs that the plugin expects Python regex, and also added the regex for the `percent` format (excluding `^` and `$` anchors) as an example to the README.
