### ISSUE TITLE
First line of code not included if tags are not present in the code

### ISSUE THREAD

**Issue by hovnatan** [hanschen/vim-ipython-cell#15]
First line of code not included if tags are not present in the code. E.g., if I have
```
from pathlib import Path

for img1 in Path("/mnt/c/").glob("*.png"):

    print(img1)

```

and press `<c-c><c-c>` somewhere in the code then `from pathlib import Path` won't be included in the execution.

**Comment by hanschen** [comment]
Ah, good catch. This was caused by the latest commit. I've pushed a fix, please update the plugin and see if it works properly now.

If you're still experiencing issues you can reopen this issue. Thanks for the report!
