### ISSUE TITLE
Lovely plugin! :) 

### ISSUE THREAD

**Issue by f1se4** [hanschen/vim-ipython-cell#17]
If you find interesting.. I have added this to my .vimrc

When I open any python file automatically my current work directory is changed to the opened file path, with this path, I could open ipython console in cwd. This helps me to read .csv path files, etc... without issues.

" Change automatically current directory to open file directory                                  
autocmd BufEnter * silent! lcd %:p:h

" map to start ipython in current file directory                                            
nnoremap <Leader>st :execute 'SlimeSend1 cd 'fnameescape(expand('%:p:h'))<CR>:execute 'SlimeSend1 clear'<CR>:SlimeSend1 ipython3<CR>

hopes it helps to improve a llitle more :)

**Comment by hanschen** [comment]
Hey, thanks for the tip and nice words. :)

I've added your tip to the newly created [wiki](https://github.com/hanschen/vim-ipython-cell/wiki). Feel free to add more tips here!
