### ISSUE TITLE
Not working in virtualenv

### ISSUE THREAD

**Issue by lsshawn** [hanschen/vim-ipython-cell#2]
When I run `:IPythonCellExecuteCell` in  virtual environment, I get 

`E492: Not an editor command: IPythonCellExecuteCell`

**Comment by hanschen** [comment]
Which operating system do you use?

Do you see the message `ipython-cell requires py >= 2.7 or py3` when you start Vim? (If the text disappears, you can check with `:messages`.)

I assume `:IPythonCellExecuteCell` works outside virtual environments?

What's the output of `:!which python`?

Do you get the same issue with other Vim plugins written in Python (e.g. [ultisnips](https://github.com/SirVer/ultisnips))?

**Comment by lsshawn** [comment]
Manjaro 18.1.2
Python 3.5.6
Ipython 4.2.0

Same error on conda virtual environment too.

**Comment by lsshawn** [comment]
Vim plugins written in Python seem to have errors too. e.g. vim-denite

**Comment by lsshawn** [comment]
I solve it with [this instruction](https://github.com/deoplete-plugins/deoplete-jedi/wiki/Setting-up-Python-for-Neovim).

After activating virtualenv:
```
pip install neovim
which python  # Note the path
```

Then add the path in `init.vim`
`let g:python3_host_prog = path/to/bin/python`

**Comment by hanschen** [comment]
Ah, I was just about to ask if you use neovim. Thanks for the update with your solution.

**Comment by Mickychen00** [comment]
Hi, I also use neovim and encounter same problem. Maybe a notification about this trick is needed for freshman. Thanks a lot!

**Comment by hanschen** [comment]
Good point, I've clarified the entry about virtual environments in the FAQ. Hope it's clearer now.

**Comment by Mickychen00** [comment]
Hi, many thanks for the updating of the FAQ for new beginner!  P.S. I use tmux as ipython terminal. I wanna know is there a good solution/choice for showing the matplotlib's plot in tmux with plot history like  in Jupyter notebook's $matplotlib inline magic?

**Comment by hanschen** [comment]
> Hi, many thanks for the updating of the FAQ for new beginner! P.S. I use tmux as ipython terminal. I wanna know is there a good solution/choice for showing the matplotlib's plot in tmux with plot history like in Jupyter notebook's $matplotlib inline magic?

Unfortunately I'm not aware of anything like that. I know there's Qt Console for Jupyter which supports inline plots, but then you would need a different Vim plugin to run the code from the editor.
