### ISSUE TITLE
Add a note on having autoreload enabled in IPython

### ISSUE THREAD

**Issue by gerazov** [hanschen/vim-ipython-cell#20]
Great plugin! :clap:

This could be used for an IDE like experience for Python using Vim. In order for things to run smoothly maybe add a note on enabling autoreload in IPython. It's not really Vim related but could be useful for users :+1:

To have IPython start with autoreload enabled you need to have a default config file `.ipython/profile_default/ipython_config.py` with the following content:

```python
c = get_config()
c.InteractiveShellApp.extensions = ['autoreload']
c.InteractiveShellApp.exec_lines = ['%autoreload 2']
```

**Comment by hanschen** [comment]
Thanks for the nice comment :smiley: I'm glad that you find the plugin useful.

I've added you tip to [the wiki](https://github.com/hanschen/vim-ipython-cell/wiki) (in a slightly different way). Let me know if you spot any mistakes.
