### ISSUE TITLE
Send cell title before sending code

### ISSUE THREAD

**Issue by gerazov** [hanschen/vim-ipython-cell#22]
Currently the cell code is sent via `%paste -q`, which is nice and tidy. 

It would be great if the cell title, i.e. declaration line, is sent before hand, or something to that effect. 

This would make it easier to keep track which code was executed in IPython. A provisional title can be given to the import cell, e.g. `Cell 0`, as it usually doesn't have a header.

Currently:
```python
In [1]: %paste -q
In [2]: %paste -q
In [3]: %paste -q
```

Suggested:
```python
In [1]: # %% Cell 0
In [2]: %paste -q
In [3]: # %% define paths
In [4]: %paste -q
In [5]: # %% load data
In [6]: %paste -q
```

**Comment by hanschen** [comment]
Try to add the following to your .vimrc/init.vim:

```vim
let g:ipython_cell_send_cell_headers = 1
```

Report back if you find any issues.

EDIT: I've now made the cell headers more nicely grouped with their corresponding `%paste -q` commands. I haven't tried all possible configurations yet so it's possible that this introduces some bugs - please let me know if you find any issues with the latest version.

**Comment by gerazov** [comment]
Works as expected thanks! :muscle:
