### ISSUE TITLE
Open terminal and run ipython (function)

### ISSUE THREAD

**Issue by argapost** [hanschen/vim-ipython-cell#23]
Hello!
I made a very basic function that opens a new terminal in a vertical split runs ipython, and connects the two splits via slime in order to use the vim-ipython-cell. 

```lua
-- Open interactive IPython
function IPythonOpen()
      vim.cmd("vnew|call termopen('ipython3')") -- open a new terminal in vertical split and run ipython
      vim.g.repl_job_id = vim.g.slime_last_channel -- take the jobid
      vim.cmd(":file ipython.py") -- name the new buffer
      vim.cmd(":wincmd p") -- move to previous window
end
```

I wonder what other people are using to connect their script with the REPL, and whether such a function can be integrated into the plugin vim-ipython-cell, so the user can call :IPythonOpen() and have a REPL ready for use with the other commands IPythonExecuteCell etc.

Thanks in advance!

**Comment by hanschen** [comment]
Hi, that's a nice idea! I tried it out using vimscript but couldn't access the g:slime_last_channel variable - do you know if there's anything special that needs to be done to get this variable?

I'm a bit hesitant whether this functionality should be bundled with the plugin, or if it's enough to add it to [the wiki](https://github.com/hanschen/vim-ipython-cell/wiki) and then let users customize it however they want.

**Comment by argapost** [comment]
Yeah, I think you are right, better in the wiki because it will depend on the configuration of each user.  Probably there is a better way to implement the same functionality, but I am no expert on either vimscript or lua.

Can you try &channel ? I think this gives the job-id of the terminal in neovim at least.

**Comment by hanschen** [comment]
I got the following to work in Neovim:

```vim
function! IPythonOpen()
    " open a new terminal in vertical split and run IPython
    vnew|call termopen('ipython --matplotlib')
    file ipython " name the new buffer

    " set slime target to new terminal
    if !exists('g:slime_default_config')
        let g:slime_default_config = {}
    end
    let g:slime_default_config['jobid'] = b:terminal_job_id
    let g:slime_target = 'neovim'
    let g:slime_dont_ask_default = 1

    wincmd p " switch to the previous buffer
endfunction
```

I think `&channel` works as well instead of `b:terminal_job_id`. Now I just need to figure out what these variables are called in Vim's terminal implementation...

Feel free to improve upon this and add it to the wiki, otherwise I'll work on it tomorrow.

**Comment by argapost** [comment]
It looks better, thanks! I have zero ideas about the vim implementation. For me, this setup works really good if you have any ideas for improvements I ll be happy to help!

**Comment by hanschen** [comment]
I've added the tip to the wiki, thanks for the idea. Feel free to add any other nice tips to the wiki.
