### ISSUE TITLE
Add command that will send line without execution

### ISSUE THREAD

**Issue by gerazov** [hanschen/vim-ipython-cell#25]
Sending a line now to IPython also executes it immediately. It would be useful to be able to edit the line before running it.

**Comment by hanschen** [comment]
Are you thinking of any particular `IPythonCell` command? I don't quite see the use case, except for maybe `IPythonCellExecuteCellVerbose`, and am hesitant to add a flag to every command to support this feature.

**Comment by gerazov** [comment]
I was thinking of SlimeLineSend, so maybe it's more of a Slime thing - is it at all possible? 

I wouldn't set a flag but rather have two commands - SlimeLineSend and SlimeLineExecute.

**Comment by hanschen** [comment]
Yeah that's more of a slime thing, so I'll close this issue.

There's a `SlimeSend1` command to send a single line of text, and `SlimeSend0` to send a line without a carriage return. You could try the latter (unfortunately it doesn't seem to be documented).
