### ISSUE TITLE
Lazy load vim-ipython-cell: turn `plugin` into `ftplugin`

### ISSUE THREAD

**Issue by sotte** [hanschen/vim-ipython-cell#26]
First of all thanks for the plugin! I use it every day.

Second: Loading vim-ipython-cell (and python2/python3 with it) slows down the startup of vim/nvim. It's actually the slowest plugin for me. One could turn this plugin (which always loads) into a ftplugin (which only loads for specific file types).

# ftplugin
I checked the startup time with [vim-plugin-profile](https://github.com/hyiltiz/vim-plugins-profile.
```
➤ python vim-profile.py -s nvim                                                               
Running nvim to generate startup logs... done.                                                
Loading and processing logs... done.                                                          
Plugin directory: /home/stefan/.vim_plugins                                                   
=====================================                                                         
Top 10 plugins slowing nvim's startup                                                         
=====================================                                                         
1       112.988   *python3.vim                                                                
2        75.636   vim-ipython-cell                                                            
3        19.273   vim-polyglot                                                                
...                                                                  
===================================== 
```

# ftplugin
Turning the plugin into a ftplugin:
```
mv plugin ftplugin
mv ftplugin/ipython_cell.vim ftplugin/python.vim
```

This speeds up loading the plugin:
```
➤ python vim-profile.py -s nvim
Running nvim to generate startup logs... done.
Loading and processing logs... done.
Plugin directory: /home/stefan/.vim_plugins
=====================================
Top 10 plugins slowing nvim's startup
=====================================
1        21.184   vim-polyglot
2        13.026   *filetype.vim
...
```

**Comment by hanschen** [comment]
Thanks for the suggestion. I'm glad to hear that you find the plugin useful. :smiley:

The reason I decided against using `ftplugin` is that some users use the plugin for languages other than Python, e.g. Julia and R. In my mind it is easier to disable the plugin for certain filetypes using your plugin manager (see README for some examples) rather than find ways to enable it if it were an `ftplugin`.

Does that make sense, or would you like to see an option to restrict the plugin to certain filetypes (for people who don't use plugin managers)?

**Comment by sotte** [comment]
I have to admit that I did not see the part about limiting loading forspecific filetypes in the README. My bad!

This is is relevant part:
```
Plug 'jpalardy/vim-slime', { 'for': 'python' }
Plug 'hanschen/vim-ipython-cell', { 'for': 'python' }
```

Thanks for the tip @hanschen!
