### ISSUE TITLE
Messing up syntax highlight

### ISSUE THREAD

**Issue by RichardLee0211** [hanschen/vim-ipython-cell#32]
Have used this plugin for several months now, very handy and beautifully done. 
Yet, oneday, It seems to mess up syntax highlight in 
macOS 20.6.0 Darwin Kernel Version 20.6.0, iterm2 3.3.12, VIM - Vi IMproved 8.2 2019 Dec 12

<img width="305" alt="Screen Shot 2021-09-10 at 15 58 38" src="https://user-images.githubusercontent.com/21286676/132911395-2f43af05-4a4d-4240-be23-e6de7d24b3ae.png">

vimrc file here: 
https://github.com/RichardLee0211/test/blob/master/tmp/vimrc.config

**Comment by hanschen** [comment]
Thanks for the report. I've pushed a fix for this, can you please update the plugin and see if it works now?

**Comment by RichardLee0211** [comment]
Yes, it does. Thanks.
