### ISSUE TITLE
:IPythonCellPrevCell won't work in visual mode

### ISSUE THREAD

**Issue by singledoggy** [hanschen/vim-ipython-cell#40]
If it possible to add a feature make it works when using visual mode?

**Comment by hanschen** [comment]
EDIT: I see now that you specified the command in the title. I'll look into it when I have time - pull requests would also be appreciated.

Previous answer:

What specifically do you want to use it for in visual mode?

To send the selected lines, you can use vim-slime (which you've installed already as a dependency), as illustrated in the [Example Vim config](https://github.com/hanschen/vim-ipython-cell#example-vim-configuration) provided in the README:

``` vim
" map <Leader>h to send the current line or current selection to IPython
nmap <Leader>h <Plug>SlimeLineSend
xmap <Leader>h <Plug>SlimeRegionSend
```

**Comment by singledoggy** [comment]
Sometimes I need to copy several cells or delete several cells, so it's useful to use the jump function in visual mode. Currently, I choose to add book marks in normal mode then jump in viusal. But it would be better if the jump function can work in visual mode.

**Comment by singledoggy** [comment]
Sometimes I want to delete some cells or copy several cells, and if the move function can work in visual mode, it will be much more convenient. ------------------ Original ------------------From: Hans Chen  ***@***.***>Date: Wed,Aug 10,2022 4:32 PMTo: hanschen/vim-ipython-cell ***@***.***>Cc: Han Yuyang ***@***.***>, Author ***@***.***>Subject: Re: [hanschen/vim-ipython-cell] :IPythonCellPrevCell won't work invisual mode (Issue #40)
What specifically do you want to use it for in visual mode?
To send the selected lines, you can use vim-slime (which you've installed already as a dependency), as illustrated in the Example Vim config provided in the README:
" map <Leader>h to send the current line or current selection to IPython
nmap <Leader>h <Plug>SlimeLineSend
xmap <Leader>h <Plug>SlimeRegionSend

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/hanschen/vim-ipython-cell/issues/40#issuecomment-1210341760",
"url": "https://github.com/hanschen/vim-ipython-cell/issues/40#issuecomment-1210341760",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
