### ISSUE TITLE
Arise "Not an editor command"

### ISSUE THREAD

**Issue by draftman9** [hanschen/vim-ipython-cell#41]
This is my vimrc:

```
let g:slime_target = "vimterminal"
nnoremap <Leader>s :SlimeSend1 ipython --matplotlib<CR>
nnoremap <Leader>r :IPythonCellRun<CR>
nnoremap <Leader>R :IPythonCellRunTime<CR>
nnoremap <Leader>c :IPythonCellExecuteCell<CR>
nnoremap <Leader>C :IPythonCellExecuteCellJump<CR>
let g:ipython_cell_run_command = 'include("{filepath}")'
let g:ipython_cell_cell_command = 'include_string(Main, clipboard())'

call plug#begin('~/vimfiles/plugged')
Plug 'jpalardy/vim-slime', { 'for': 'python' }
Plug 'hanschen/vim-ipython-cell', { 'for': 'python' }
call plug#end()
```

When I use these command in julia file(.jl), the vim arise message: Not an editor command blabla. I execute `:echo has("python3")`  and it return 1. That confuse me a lot.

![image](https://user-images.githubusercontent.com/99490289/186630807-a494c21e-0694-4371-b1fc-7ff9302f93c4.png)
![image](https://user-images.githubusercontent.com/99490289/186630836-55f92a86-e2d9-44e4-9225-9acab0392035.png)

BTW: I firstly install the two plugins without `{'for': 'python'}` because I want it to support julia. Expectedly it does not work. So I deleted the two plugin files from their path and added `{'for': 'python'}` before re-installing the two plugins. However it does not work perfectly.

**Comment by hanschen** [comment]
Yeah, you want to remove the `{'for': 'python'}` part if you want to use the plugins for Julia. What error do you get if you try to install it with:

``` vim
call plug#begin('~/vimfiles/plugged')
Plug 'jpalardy/vim-slime'
Plug 'hanschen/vim-ipython-cell'
call plug#end()

```

**Comment by draftman9** [comment]
After `:SlimeSend1 ipython --matplotlib<CR>` and `:IPythonCellRun<CR>`, the messages arose in the picture. The second one I think it is induced by the sequence of '\\', which should be replaced by '/'.

![image](https://user-images.githubusercontent.com/99490289/186870140-3cbd90d7-a6b1-4df1-a98e-3b28ac96d82b.png)
![image](https://user-images.githubusercontent.com/99490289/186870118-a9820328-ff61-4b42-a941-a1971d199c72.png)

**Comment by hanschen** [comment]
Can you try the following and see if it works?

``` vim
let g:ipython_cell_run_command = 'include(raw"{filepath}")'
```

For the first command, that is for starting IPython in the shell. You might want to change the command to `:SlimeSend1 julia<CR>` or something similar, and run it in the regular bash/zsh/etc. shell, not in the Julia interpreter.
