### ISSUE TITLE
"Not an editor command" on Mac

### ISSUE THREAD

**Issue by uygarkurt** [hanschen/vim-ipython-cell#43]
Hey, thank you for this amazing plugin. Just what I was looking for :)

I'm on mac. I installed new version of Vim with:

`brew install vim`

currently `echo has('python3')` returns `1`.

My .vimrc looks like the following:
`call plug#begin("~/.vim/plugged")`
`Plug 'sheerun/vim-polyglot'`
`Plug 'preservim/nerdtree'`
`Plug 'jpalardy/vim-slime', { 'for': 'python' }`
`Plug 'hanschen/vim-ipython-cell', { 'for': 'python' }`
`call plug#end()`

`:PlugInstall` and everything is installed withoud an error.

However when I type `vim` to the terminal(default mac terminal) and do `:IPythonCellExecuteCell` I get an `Not an editor command` error. I can't figure it out. Would appreciate any support.

**Comment by hanschen** [comment]
Hey, you have included `'for': 'python'`, so the plugin will only load for Python files.

Try to either remove that part after `vim-slime` and `vim-ipython-cell`, or open a Python file (`vim example.py`).

Hope that helps!

**Comment by uygarkurt** [comment]
thank you :)
