### ISSUE TITLE
:IPythonCellRunTime do not reload functions when they are modified in another script

### ISSUE THREAD

**Issue by arafive** [hanschen/vim-ipython-cell#47]
Hi! I have two scripts: test.py and my_func.py in the same directory

test.py is:
```
from my_func import print_name_age

name = 'Daniele'
print_name_age(name)
```

and my_func.py
```
def print_name_age(name, age=30):
    print(f"I am {name}, I am {age}")
```

In tmux with 3 terminal, I open test.py, my_func.py and in the last one I lunch ipython with :SlimeSend1 ipython

Everything works fine on console, but if I change something in print_name_age function (let's say, age=20), and re-run the code, nothing changed: Daniele has always 30 years.

Why?

Using Vim 8.1.1847 or Nvim 0.9.5, the problem is the same.

Thanks!

**Comment by hanschen** [comment]
I believe the problem you're running into is related to IPython and not this specific plugin. See this page for how to solve it: https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html

You can put this in a [startup file](https://ipython.readthedocs.io/en/stable/interactive/tutorial.html#startup-files) to enable auto-reloading.

Closing this issue as it's related to IPython. Feel free to re-open if I've misunderstood the problem.

**Comment by arafive** [comment]
Yes that was. I have also seen this guide: [https://dev.to/abbazs/how-to-set-autoreload-in-ipython-at-startup-16cl](https://dev.to/abbazs/how-to-set-autoreload-in-ipython-at-startup-16cl)

It's really strange for me that something like this is not the "default" IPython behavior (I have ipython 8.22.1)

Thanks!
