### ISSUE TITLE
Error: Can't open display: (null)

### ISSUE THREAD

**Issue by g3g3n3** [hanschen/vim-ipython-cell#6]
I can get your plugin to run the whole script, restart the ipython shell, clear the ipython screen, etc. but I cannot get it to run just a cell, with either "marks" or "tags".

In vim I get the following error:

`Error: Can't open display: (null)`

and in the ipython shell I get:

```
%paste -q
File "<ipython-input-6-5f93bd8b4c58>", line 1
    "------------------------------------------------------------------------------
                                                                                            ^
SyntaxError: EOL while scanning string literal
```

I tried changing this setting to both 0 and 1
`let g:slime_python_ipython = 1`

I just had a simple test script: (top is mark a, bottom is mark b)

```
x = 5
print(x)
print('top')

print('bottom')

```
I'm using the most recent version of vim, tmux and ipython on MacOS.
Thanks!

**Comment by hanschen** [comment]
Do you have xclip or xsel installed? Can you use these programs from the command line?
Note that when you re-attach a tmux session you may have to update the DISPLAY variable, e.g. with `eval $(tmux showenv -s DISPLAY)`.

**Comment by g3g3n3** [comment]
Yes, I have xclip installed. 
I can get it to copy a whole file, but it doesn't seem to copy raw text, or at least I'm not sure how it works.

xsel may work on macos but it requires x11.
pbcopy/pbpaste is apparently best for macos.

When I use `\ c` it does not select the text in vim, but rather, it will send the text that I have in my clipboard. The error message includes the clipboard text and returns a syntax error. (because it's not a Python command).

For example if I copy the text `flying_circus` to my clipboard, then go to the vim file and use `\ c` I will get the following error:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-11-3af5855b4a4d> in <module>
----> 1 flying_circus

NameError: name 'flying_circus' is not defined
```
I start a new tmux session every time, so I don't think it's a problem with DISPLAY variable.
Thanks.

**Comment by hanschen** [comment]
I've added support for using pbcopy, could you please update the plugin and see if it works now?

**Comment by g3g3n3** [comment]
WOW! That works **BEAUTIFULLY**! 
Thank you!

**Comment by hanschen** [comment]
Great to hear that it works now, thanks for your feedback.
