### ISSUE TITLE
Starting a session with IPythonCellExecuteCellJump fails

### ISSUE THREAD

**Issue by samuell** [hanschen/vim-ipython-cell#7]
First, thanks for a super-userful plugin! :+1: :+1: 

Bug: If I start my session with `:IPythonCellExecuteCellJump`, I will only end up with the following:

```
In [1]: %cpaste -q
--
```

Then, when doing the next of the same command, I will get:

```
  File "<ipython-input-1-fb5d34668dfb>", line 1
    ##
    ^
SyntaxError: invalid syntax
```

On the other hand, if I start with `:IPythonCellExecuteCell` (without the jump), then it works fine as I continue using both `:IPythonCellExecuteCell` and `:IPythonCellExecuteCellJump`.

System info:

- Xubuntu 18.04 64bit
- Python 3.7.7
- VIM 8.0 (2016 Sep 12, compiled Mar 18 2020 18:29:15) (Included patches: 1-1453)
- IPython 7.13.0
- Vim-IPython-cell version: master, commit: df3d980b979a07e222809b55c9cfb7860a1e593d
- TMux 2.6

Relevant .vimrc Config (Btw, the `let g:ipython_cell_valid_marks = '#%%'` doesn't seem to work, so I'm still using `##` as cell separator):

```vimrc
" ---------------------------------------------------------------------------
" Vim plug (https://github.com/junegunn/vim-plug)
" ---------------------------------------------------------------------------

"Specify a directory for plugins
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugs')

" Python stuff
Plug 'jpalardy/vim-slime', { 'for': 'python' }
Plug 'hanschen/vim-ipython-cell', { 'for': 'python' } " https://github.com/hanschen/vim-ipython-cell
Plug 'davidhalter/jedi-vim', { 'for': 'python' }

" Go stuff
Plug 'fatih/vim-go', { 'for': 'go' }

" Initialize plugin system
call plug#end()

" ---------------------------------------------------------------------------
" Vim IPython Cell / Slime
" ---------------------------------------------------------------------------

let g:slime_target = "tmux"

let g:ipython_cell_delimit_cells_by = 'tags'
let g:ipython_cell_valid_marks = '#%%'

" map <Leader>c to execute the current cell
nnoremap <Leader>c :IPythonCellExecuteCell<CR>

" map <Leader>C to execute the current cell and jump to the next cell
nnoremap <Leader>C :IPythonCellExecuteCellJump<CR>
```

**Comment by hanschen** [comment]
Thanks for the report, glad to hear that you find the plugin useful. :smiley:

Can you try to update and see if it works now? The error you saw was likely due to a small mix-up that led `IPythonCellExecuteCellJump` to actually use `IPythonCellExecuteCellVerboseJump`.

It's still weird that the verbose version doesn't work for you. If you have time, could you please try `:IPythonCellExecuteCellVerboseJump` and see if you get the same error as before?

To use `'#%%'` as your cell headers, try

    let g:ipython_cell_tag = '#%%'

instead of `g:ipython_cell_valid_marks`.

**Comment by hanschen** [comment]
Closed due to inactivity. Feel free to reopen if the issue is still present.
