### ISSUE TITLE
Send quit command to ipython to get out of debugger

### ISSUE THREAD

**Issue by jorgsk** [hanschen/vim-ipython-cell#8]
I use the ipython debugger frequently and it would be convenient to also be able to quit the debugger from vim.

Adding a command such as IPythonCellPDBQuit would work.

**Comment by hanschen** [comment]
Does the following work?

    " map <Leader>d to start debug mode
    nnoremap <Leader>d :SlimeSend1 %debug<CR>
    
    " map <Leader>q to exit debug mode or IPython
    nnoremap <Leader>q :SlimeSend1 exit<CR>

Also thanks for the pull request! However, I would prefer that people just use `SlimeSend1` rather than adding every possible IPython command to this plugin. I've added a tip about this command in the README (8edd8c51fdee5c2a2d884bb6a71a9cd68ecd2329).

**Comment by jorgsk** [comment]
That works well, thanks, I wasn't aware of SlimeSend1! No problem, I'll retract the pull request.
